version: '3'

services:
  app:
    build:
      context: .docker/app
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./api/:/var/www
    networks:
      - ahs-net    

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - ahs-net

  nginx:
    build: .docker/services/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./api/:/var/www
    networks:
      - ahs-net


networks:
  ahs-net:
    driver: bridge